### ISSUE TITLE
Creating a clear PM process

### ISSUE THREAD

**Issue by samsontmr** [OpenMined/docs#10]
The aim here is to come up with a structured and transparent workflow/process that we will use to decide what goes into each release. This can then be standardized in all of our projects, which will be extremely useful when we have different PMs for each project.

The approach I'm leaning towards to is Story Mapping, described [here](https://www.thoughtworks.com/es/insights/blog/story-mapping-visual-way-building-product-backlog).

**Comment by anoff** [comment]
We test-drove an idea yesterday, let's see how this plays out. I'll try to formalise what we did.

**Comment by samsontmr** [comment]
@anoff Looking forward to hearing it!

**Comment by anoff** [comment]
shit forgot to ref this issue :( check the `feature_evolution_process`
