### ISSUE TITLE
Add CLA bot to all repositories

### ISSUE THREAD

**Issue by adrianbrink** [OpenMined/docs#17]
Normally it is a good idea to add an explicit CLA bot to all repositories where a lot of contributors contribute code.

Under normal circumstances everyone that contributes code implicitly accepts the license of the repository. However I doesn't hurt to protect ourselves from potential law suits by adding a super short explicit acceptance step using the [CLA bot](https://cla-assistant.io/).

I don't mind implementing this for all the repos as I have done it before.

**Comment by anoff** [comment]
Hah awesome! Had that open this morning. I say go ahead and set it up :)

**Comment by kevinahuber** [comment]
@adrianbrink any progress on this? Happy to take it up.

**Comment by adrianbrink** [comment]
@kevinahuber I am trying but for some weird reason it doesn't show up on the website and hence I cannot setup the webhooks.

@iamtrask Either you can [try](cla-assistant.io) or I would need to experiment with the level of admin access that you can give me.
