### ISSUE TITLE
Funneling new users into projects easier

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/docs#36]
I'm trying to wrap my mind around how we might guide new users exploring OpenMined for the first time to join a specific project.  It's hard for people to grasp the entire ecosystem and so often they join Slack without much aim of where they can best fit in.  If we formed teams, naturally this might fall into place... but for the time being, we need some means of directing people according to their skills and interests.  I would propose the following system (i.e. Machine Learning):

### Machine learning
**Repositories:**
- [PySonar](https://github.com/OpenMined/PySonar) - Python client to blockchain application (Sonar)
- [PySyft](https://github.com/OpenMined/PySyft) - Python deep learning library
- [syft.js](https://github.com/OpenMined/syft.js) - Node.js deep learning library (for web and mobile browsers)

**Slack channels:** #sonar, #syft

This gives people a high-level overview of what repositories are important and what Slack channels contain the primary discussion on the matter.  Other things we could do would be to include a link to the top contributors of a project (so they can be accessible for DM by an individual to get caught up).  These individuals would act as pseudo "team leaders" basically implied from how much they've contributed to a project.  We also may want to include a link to the issues pages directly so that people can see the actual work that needs to get done.

Open for thoughts here.  I've already begun addressing this [in the following pull request](https://github.com/OpenMined/Docs/pull/35).  Please feel free to contribute and discuss!

**Comment by cereallarceny** [comment]
Originally I was thinking that it would be best to list all the projects going on in the OpenMined community.  The problem with that is if a contributor is just arriving at the OpenMined, then they have no idea what the projects are.  Instead, I opted to list potentially needed skill sets and state where they would best fit in.  That's my current thought process.

**Comment by anoff** [comment]
Great proposal! I put some nitpicks reviews in the corresponding PR ;)

**Comment by cereallarceny** [comment]
This is a wrap.
